services:
  db:
    image: postgres:16
    container_name: workforce-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: ${IMAGE}
    container_name: workforce-api
    env_file:
      - .env
    # Bind container port 3000 to host loopback 3000 for Nginx upstream
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
